url: "http://dt106ers.com"
name: DT106ers New Planners Blog
baseurl: /dt106ers.com_jekyll

wind:
  name: Archive - DT106ers New Planners Blog
  description: >
    Everything to do with Spatial Planning
    especially Ireland but around the world
  author:
    name: Colin Broderick
    url: http://cbroderick.me/
    linkedin: http://ie.linkedin.com/in/colinbroderick/
    twitter: http://www.twitter.com/rusty1052
    github: http://www.github.com/rustyb
  lang: en
  stylesheets:
    - /css/extra.css
  favicons:
    - /assets/2014/04/21/favicon-152.png
  topbar:
    toggle: Menu
    right:
      - name: Home
        url: /dublin/
      - name: About
        url: /about/
      - name: Archives
        url: /archives/